teams_dictionary = {
    1678:{
		"location":"Davis_CA_USA",
		"rookie_year":"2005",
		"2019_comp_status":True,
		"2019_comp_name":[
			"Central_Valley_Regional",
			"Sacramento_Regional",
			"Aerospace_Valley_Regional",
			"Carver_Division",
			"Einstein_Field_Houston",
			"RCC_Qianjiang_International_Robotics_Invitational",
			"Chezy_Champs"],
		"2019_comp_location":[
			"Fresno_CA_USA",
			"Davis_CA_USA",
			"Lancaster_CA_USA",
			"Houston_TX_USA",
			"Houston_TX_USA",
			"Hangzhou_Zhejiang_CHN",
			"SanJose_CA_USA"],
		"2019_season_awards":[
			"Regional_Chairmans",
			"Regional_Winners",
			"Deans_List_Finalist",
			"Regional_Winners",
			"Industrial_Design",
			"Regional_Winners",
			"Excellence_Engineering",
			"Championship_Subdivision_Winner"]},
	5000:{
		"location":"Hingham_MA_USA",
		"rookie_year":"2014",
		"2019_comp_status":True,
		"2019_comp_name":[
			"NE_District_SE_Mass_Event",
			"NE_District_Rhode_Island_Event"],
		"2019_comp_location":[
			"Bridgewater_MA_02324_USA",
			"Smithfield_RI_02917_USA"],
		"2019_season_awards":[]},
	69:{
		"location":"Quincy_MA_USA",
		"rookie_year":"1998",
		"2019_comp_status":True,
		"2019_comp_name":[
			"NE_District_SE_Mass_Event",
			"NE_District_UNH_Event",
			"New_England_District_Championship"],
		"2019_comp_location":[
			"Bridgewater_MA_02324_USA",
			"Durham_NH_03824_USA",
			"Worcester_MA_USA"],
		"2019_season_awards":[
			"District_Event_Finalist",
			"Creativity_Award_sponsored_by_Xerox",]},
	590:{
		"location":"Choctaw_MS_USA",
		"rookie_year":"2001",
		"2019_comp_status":True,
		"2019_comp_name":[
			"Bayou_Regional"],
		"2019_comp_location":[
			"Kenner_LA_70065_USA"],
		"2019_season_awards":[]},
	3686:{
		"location":"Memphis_TN_USA",
		"rookie_year":"2011",
		"2019_comp_status":False,
		"2019_comp_name":[],
		"2019_comp_location":[],
		"2019_season_awards":[]}
}